"""Add recommendations column to CV model

Revision ID: 1594f79ab935
Revises: 
Create Date: 2025-03-27 02:11:16.378043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1594f79ab935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('recommendations')

    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('skill', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
